using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using api.EntityFrameworkCore;


namespace ECommerceAPI.Models
{
  [Table("UserWithDataAnnotation")]
  public class UserWithDataAnnotation
  {
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public Guid UserId { get; set; }

    [Required]
    [StringLength(100)]
    public string Name { get; set; } = string.Empty;

    [Required]
    [StringLength(100)]
    [EmailAddress]
    [Column("email", TypeName = "varchar(100)")]
    public string Email { get; set; } = string.Empty;

    [Required]
    [StringLength(255)]
    public string Password { get; set; } = string.Empty;

    [StringLength(255)]
    public string Address { get; set; } = string.Empty;

    [StringLength(255)]
    public string Image { get; set; } = string.Empty;

    [Column("isAdmin", TypeName = "boolean")]
    public bool IsAdmin { get; set; } = false;

    [Column("isBanned", TypeName = "boolean")]
    public bool IsBanned { get; set; } = false;

    [Column("createdAt", TypeName = "timestamp with time zone")]
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public List<Order> Orders { get; set; } = new List<Order>();  // One-to-many with Order
  }
}

/*
Key Attributes and Annotations Explained:
[Table("Users")]: Specifies the table name in the database.

[Key], [DatabaseGenerated(DatabaseGeneratedOption.Identity)]: Indicates that UserId is the primary key and its value should be generated by the database when a new record is inserted.

[Required]: Specifies that a field is mandatory.

[StringLength(100)]: Limits the maximum length of the string fields (Name and Email) to 100 characters.

[EmailAddress]: Ensures the Email field conforms to a valid email format.
[Column(TypeName = "varchar(100)")]: Explicitly maps Email to a column in the database with the specified type, which is particularly useful when using specific SQL data types like varchar.

[StringLength(255)]: Used for fields like Password, Address, and Image to specify maximum length.

[Column("isAdmin", TypeName = "boolean")] and [Column("isBanned", TypeName = "boolean")]: Maps the IsAdmin and IsBanned properties to columns in the database and specifies their types. These fields also have default values set to false.

[Column("createdAt", TypeName = "timestamp")]: Specifies that CreatedAt should map to a timestamp column and is initialized with the current date and time.
*/